### PR TITLE
[Add]:landing_page_BG_transition

### PR DESCRIPTION
**Pull request by infern018**
ezgif com-gif-maker (1)

Hey @abhikhedekar4241  regarding your last suggestions, I have added some background transitions, please have a look...

### CODE REVIEW

**Comment by abhikhedekar4241** [comment]
good work @infern018

**Comment by abhikhedekar4241** [comment]
Actually there was dark mode and light mode transition switch. It is not working now.

**Comment by infern018** [comment]
thanks @abhikhedekar4241 , also wanted to state an issue that the dark<->light mode toggle button can be clicked only when cursor is placed on it's top area.

**Comment by infern018** [comment]
> Actually there was dark mode and light mode transition switch. It is not working now. @infern018

yes actually only it's top area is clickable, I tried to solve that but was facing some problems, will look into it.

**Comment by abhikhedekar4241** [comment]
> > Actually there was dark mode and light mode transition switch. It is not working now. @infern018
> 
> yes actually only it's top area is clickable, I tried to solve that but was facing some problems, will look into it.

Yes Please

**Pull request merged**
